### ISSUE TITLE
US 01.01.01

### ISSUE THREAD

**Issue by Sohaib404** [CMPUT301F21T19/Habitappt#16]
As a doer, I want to add a habit, giving it a brief title, reason, and date to start. 
- Story Points: 1		
- Risk: LOW
- Half-Way Checkpoint

## Tasks

- [x] Create habit class
- [ ] Create view habit fragment
- [ ] Create edit habit activity
