### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by Sohaib404** [CMPUT301F21T19/Habitappt#31]
Write runnable tests for your model and control classes. Provide intent tests for the requirements you have done. Deliver the test code to your source repository. If you have test data files, also include those. Test data should be realistic.

## Tasks

- [ ]  Testing adding a new Habit
- [ ]  Testing deleting a Habit
-  [ ]  Testing editing a Habit
- [ ]  Testing adding a new Habit Event

**Comment by Sohaib404** [comment]
We didn't end up using this issue to track test cases.
