### ISSUE TITLE
US 01.01.01 [updated]

### ISSUE THREAD

**Issue by the-rooster** [CMPUT301F21T19/Habitappt#33]
As a doer, I want to add a habit, giving it a brief title, reason, date to start, and whether it is public or private.

## Tasks
- [x] Create habit class
- [x] Create unique ID numbers for each habit
- [x] Create "edit habit" fragment for editing and adding habits
- [x] #75
- [x] #76
