### ISSUE TITLE
US 01.04.01

### ISSUE THREAD

**Issue by Sohaib404** [CMPUT301F21T19/Habitappt#39]
As a doer, I want to edit the details of a habit of mine.

## Tasks
- [x] Edit habit UI Implementation
- [x] Edit habit functionality
- [x] Integration with firebase
- [x] #78

**Comment by the-rooster** [comment]
[https://github.com/CMPUT301F21T19/Habitappt/commit/7468de35d1da05f1a1e7e7ae33073a904b1bce49](url)

**Comment by the-rooster** [comment]
https://github.com/CMPUT301F21T19/Habitappt/commit/54ee01790d5506f50b09a554347029401efc6d44
