### ISSUE TITLE
US 2.01.01

### ISSUE THREAD

**Issue by Sohaib404** [CMPUT301F21T19/Habitappt#45]
As a doer, I want to denote a habit event when I have done a habit as planned.

## Tasks
- [x] Habit Event List
- [x] Habit Event List Items
- [x] Edit Habit Event

**Comment by the-rooster** [comment]
https://github.com/CMPUT301F21T19/Habitappt/commit/472a7b970084478c7c32daab70695a28b9e33e7f
